name: 'flight_finder'
channels:
    - conda-forge
    - defaults
dependencies:
    - dash
    - dash-bootstrap-components
    - plotly
    - pip
    - pandas
    - altair
    - pip:
        - dash-vega-components
